# We deliberately don't use travis's language=python option because
# we install miniconda and use conda to get python. Additionally,
# Travis's auto-install of python doesn't work on osx images (see
# https://github.com/travis-ci/travis-ci/issues/4729).

# This file should be using semantically named doit commands defined in
# dodo.py
language: generic
sudo: false
os:
  - linux

env:
  global:
    - PYENV_VERSION=3.7

stages:
  - name: build_project
    if: commit_message =~ /^.*(build:).*$/

jobs:
  include:
    - &build_project
      <<: *test_project
      stage: build_project
      env: DIR=attractors
      if: |
        (commit_message =~ concat(^.*,env(DIR),.*$)) OR
        (commit_message =~ /^.*(build:all).*$/)
      script:
        - doit archive_project --name $DIR
        - travis_wait 30 anaconda-project prepare --directory $DIR
        - source activate $DIR/envs/default && pip install pyctdev
        - conda install -y "pyviz/label/dev::nbsite>=0.6.5" holoviews sphinx_pyviz_theme selenium phantomjs nomkl
        - conda install 'conda-forge::lxml'
        - doit build_project --name $DIR
      after_success:
        - git config user.email "travis@travis.org"
        - git config user.name "travis"
        - mv ./doc/$DIR ./tmp
        - git fetch https://github.com/$TRAVIS_REPO_SLUG.git evaluated:refs/remotes/evaluated
        - git diff
        - git checkout evaluated || travis_terminate 1
        - if [ -e  ./doc/$DIR ]; then rm -rf ./doc/$DIR; fi
        - mkdir ./doc/$DIR
        - mv ./tmp/* ./doc/$DIR
        - git add ./doc/$DIR
        - git commit -m "adding $DIR"
        - git push -f -q "https://pyviz-developers:$GITHUB_TOKEN@github.com/pyviz-topics/examples.git" HEAD:evaluated

    - <<: *build_project
      env: DIR=bay_trimesh

    - <<: *build_project
      env: DIR=boids

    - <<: *build_project
      env: DIR=census

    - <<: *build_project
      env: DIR=euler

    - <<: *build_project
      env: DIR=gapminders

    - <<: *build_project
      env: DIR=gerrymandering

    - <<: *build_project
      env: DIR=glaciers

    - <<: *build_project
      env: DIR=gull_tracking

    - <<: *build_project
      env: DIR=heat_and_trees

    - <<: *build_project
      env: DIR=hipster_dynamics

    - <<: *build_project
      env: DIR=landsat

    - <<: *build_project
      env: DIR=lsystems

    - <<: *build_project
      env: DIR=ml_annotators
      
    - <<: *build_project
      env: DIR=network_packets

    - <<: *build_project
      env: DIR=nyc_taxi

    - <<: *build_project
      env: DIR=opensky

    - <<: *build_project
      env: DIR=portfolio_optimizer

    - <<: *build_project
      env: DIR=square_limit

    - <<: *build_project
      env: DIR=sri_model

    - <<: *build_project
      env: DIR=uk_researchers

    - <<: *build_project
      env: DIR=iex_trading

    - <<: *build_project
      env: DIR=voila_gpx_viewer

    - <<: *build_project
      env: DIR=walker_lake

    - &local_project
      stage: build_project
      env: DIR=osm
      if: |
        (commit_message =~ concat(^.*,env(DIR),.*$)) OR
        (commit_message =~ /^.*(build:all).*$/)
      script: echo 'Need to build locally and check in to evaluated' && exit 1;

    - <<: *local_project
      env: DIR=datashader_dashboard

notifications:
  email: false
