name: docs

on: [push]

jobs:
  build_docs:
    name: Documentation
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
    timeout-minutes: 120
    defaults:
      run:
        shell: bash -l {0}
    env:
      DESC: "Documentation build"
      CHANS_DEV: "-c pyviz/label/dev -c conda-forge"
    if: "contains(github.event.head_commit.message, 'build:') || github.ref == 'refs/heads/master'"
    steps:
      - uses: actions/checkout@v2
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow -f
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
      - name: conda setup
        run: |
          conda config --set always_yes True
          conda install -c pyviz "pyctdev>=0.5"
          doit ecosystem_setup
          doit env_create ${{ env.CHANS_DEV}} --python=3.7
      - name: doit develop_install
        run: |
          eval "$(conda shell.bash hook)"
          conda activate test-environment
          conda install -y -c pyviz/label/dev "nbsite>=0.6.5" sphinx_pyviz_theme lxml pyyaml holoviews nomkl
      - name: checkout evaluated
        run: |
          git checkout -b deploy-${GITHUB_REF#refs/*/}
          git fetch https://github.com/${GITHUB_REPOSITORY}.git evaluated:refs/remotes/evaluated
          git checkout evaluated -- ./doc
      - name: build docs
        run: |
          eval "$(conda shell.bash hook)"
          conda activate test-environment
          doit build_website
          doit index_symlinks
      - name: Deploy dev
        uses: peaceiris/actions-gh-pages@v3
        if: "!contains(github.event.head_commit.message, 'website_release')"
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: pyviz-dev/examples
          publish_dir: ./builtdocs
          force_orphan: true
      - name: Deploy main
        if: "contains(github.event.head_commit.message, 'website_release')"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./builtdocs
          cname: examples.pyviz.org
          force_orphan: true
